# Site settings
title: Women in Tech (WIT) Learning Program
tag_text: Women in Tech (WIT) Learning Program
description: Website
url: ""
baseurl: "/good-clean-read"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
